name: C++ CI with Make

on:
  push:
    branches: [branchHTTPserver]
  pull_request:
    branches: [branchHTTPserver]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev
      - name: Generate configure script
        run: |
          autoreconf --install
      - name: QEMU install
        uses: docker/setup-qemu-action@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Run tests
        run: make check

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-suite.log

      - name: build ls
        run: docker buildx ls

      - name: Log in to dockerhub
        run: |
          if [[ -z "${{ vars.DOCKER_USERNAME }}" || -z "${{ secrets.DOCKER_PASSWORD }}" ]]; then
            echo "Error: DOCKER_USERNAME or DOCKER_PASSWORD is missing."
            exit 1
          fi
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Build Dockerfile image for amd64
        run: docker build --platform=linux/amd64 -t bohdanbezdrabko/httpserver:amd64 --push .

      - name: Build Dockerfile image for arm64
        run: docker build --platform=linux/arm64 -t bohdanbezdrabko/httpserver:arm64 --push .

      - name: Create manifest
        run: docker manifest create bohdanbezdrabko/httpserver --amend bohdanbezdrabko/httpserver:amd64 --amend bohdanbezdrabko/httpserver:arm64

      - name: Push manifest to docker hub
        run: docker manifest push bohdanbezdrabko/httpserver
